name: "Push changes to Stoplight"
description: "Pushes all changes for a single project on the current to Stoplight"
inputs:
  name:
    required: true
    description: "Name of the project inside the projects directory"
  token:
    required: true
    description: "CI token of the project on Stoplight to push to"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5.2

    - name: Replace image URLs in .md files
      shell: bash
      run: cd projects/${{ inputs.name }}/docs && find . -type f -name '*.md' -exec sed -i -r 's_\]\([./]+/assets/_](https://raw.githubusercontent.com/cultuurnet/apidocs/${{ steps.branch-name.outputs.current_branch }}/projects/${{ inputs.name }}/assets/_g' {} +

    - name: Publish
      shell: bash
      run: npx @stoplight/cli@5 push -d projects/${{ inputs.name }} -b ${{ steps.branch-name.outputs.current_branch }} --ci-token ${{ inputs.token }} --verbose
