name: "Get branches from Stoplight project"
description: "Returns an array containing JSON objects with info about every branch on Stoplight for a project"
inputs:
  jwt:
    required: true
    description: "JWT to authorize HTTP requests to the Stoplight API"
  projectId:
    required: true
    description: "ID of the project to get branches from"
runs:
  using: "composite"
  steps:
    - name: Get Stoplight branches
      id: getBranches
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://publiq.stoplight.io/api/v1/projects/${{ inputs.projectId }}/branches'
        method: 'GET'
        customHeaders: '{"authorization": "Bearer ${{ env.jwt }}"}'

    - name: Set Stoplight branches in output
      shell: bash
      run: echo "branches='${{ toJson(fromJson(steps.getBranches.outputs.response).items) }}'" >> $GITHUB_OUTPUT
