name: "Get JWT for Stoplight API HTTP requests"
description: "Gets a JWT for a given username/password on a configurable Stoplight workspace."
inputs:
  workspaceId:
    required: true
    description: "ID of your Stoplight workspace to get a JWT for"
  username:
    required: true
    description: "Username of a Stoplight user of the workspace"
  password:
    required: true
    description: "Password of a Stoplight user of the workspace"
runs:
  using: "composite"
  steps:
    - name: Get JWT
      id: getJwt
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://publiq.stoplight.io/api/v1/auth/login'
        method: 'POST'
        customHeaders: '{"content-type": "application/json"}'
        data: '{
          "workspaceIntegrationId": "${{ inputs.workspaceId }}", 
          "username": "${{ inputs.username }}",
          "password": "${{ inputs.password }}",
          "source": "web"
        }'

    - name: Set the JWT in the output
      shell: bash
      run: echo "jwt=${{ fromJson(steps.getJwt.outputs.response).token }}" >> $GITHUB_OUTPUT

