name: Clean Stoplight Branches
on:
  workflow_dispatch:
  push:
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clean branches in Stoplight project
        uses: ./.github/actions/stoplight-clean-branches
        with:
            workspaceId: ${{ secrets.STOPLIGHT_WORKSPACE_ID }}
            username: ${{ secrets.STOPLIGHT_USERNAME }}
            password: ${{ secrets.STOPLIGHT_PASSWORD }}
