name: Linting (Docs)
on: push
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout
          uses: actions/checkout@v3
      -   name: Lint Markdown docs
          run: yarn && yarn docs:lint
