name: Fix linting errors in docs
on: workflow_dispatch
jobs:
  docs-lint-fix:
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout
          uses: actions/checkout@v2
          with: 
            # We need to use a PAT for the dev@publiq.be user to commit the changes in that user's name. Otherwise it would be committed
            # by a "Github Actions" user, which would not trigger a new workflow run, preventing the CI checks from running after this
            # fixer job has run.
            # If the PAT ever expires or stops working, log in as dev@publiq.be on Github (see Bitwarden) and then generate a new PAT
            # at https://github.com/settings/tokens
            # For more info, see https://github.com/stefanzweifel/git-auto-commit-action#commits-made-by-this-action-do-not-trigger-new-workflow-runs
            token: ${{ secrets.PAT_DEV_AT_PUBLIQ }}
      -   name: Lint & fix Markdown docs
          run: yarn && yarn docs:lint:fix
      -   name: Push changes back to repository
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: Linting™
