name: Linting (OpenAPI)
on: push
jobs:
  openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint OpenAPI file(s)
        run: yarn && yarn api:lint
