name: Publish museumPASSmusées documentation
on:
  push:
    paths:
      - 'projects/museumpassmusees/**'
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish
        uses: ./.github/actions/stoplight-push
        with:
          name: museumpassmusees
          token: ${{ secrets.CI_TOKEN_MPM }}
          event: ${{ github.event_name }}
