name: Publish Widgets
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish
        uses: ./.github/actions/stoplight-push
        with:
          name: widgets
          token: ${{ secrets.CI_TOKEN_WIDGETS }}
