name: Publish uitpas documentation
on:
  push:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish
        uses: ./.github/actions/stoplight-push
        with:
          name: uitpas
          token: ${{ secrets.CI_TOKEN_UITPAS }}
          event: ${{ github.event_name }}
