name: Publish authentication documentation
on:
  push:
    paths:
      - 'projects/authentication/**'
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish
        uses: ./.github/actions/stoplight-push
        with:
          name: authentication
          token: ${{ secrets.CI_TOKEN_AUTHENTICATION }}
          event: ${{ github.event }}
