name: Publish Widgets
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish
        run: cd projects/widgets && npx @stoplight/cli@5 push --ci-token ${{ secrets.CI_TOKEN_WIDGETS }}
