name: Publish api design guidelines documentation
on:
  push:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish
        uses: ./.github/actions/stoplight-push
        with:
          name: api-design-guidelines
          token: ${{ secrets.CI_TOKEN_GUIDELINES }}
          event: ${{ github.event_name }}
