name: Publish authentication documentation
on:
  push:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        uses: ./.github/actions/stoplight-push
        with:
          name: authentication
          token: ${{ secrets.CI_TOKEN_AUTHENTICATION }}
          event: ${{ github.event_name }}
