name: Publish uitdatabank documentation
on:
  push:
    paths:
      - 'projects/uitdatabank/**'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish
        uses: ./.github/actions/stoplight-push
        with:
          name: uitdatabank
          token: ${{ secrets.CI_TOKEN_UITDATABANK }}
          rename-main-to-unreleased: true
