name: Publish widgets documentation
on:
  push:
    paths:
      - 'projects/widgets/**'
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish
        uses: ./.github/actions/stoplight-push
        with:
          name: widgets
          token: ${{ secrets.CI_TOKEN_WIDGETS }}
          event: ${{ github.event }}
