name: Publish errors documentation
on:
  push:
    paths:
      - 'projects/errors/**'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish
        uses: ./.github/actions/stoplight-push
        with:
          name: errors
          token: ${{ secrets.CI_TOKEN_ERRORS }}
          rename-main-to-unreleased: true
