name: Publish uitdatabank documentation
on:
  push:
    paths:
      - 'projects/uitdatabank/**'
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Publish
        uses: ./.github/actions/stoplight-push
        with:
          name: uitdatabank
          token: ${{ secrets.CI_TOKEN_UITDATABANK }}
          event: ${{ github.event_name }}
