name: Split UDB3 JSON schemas
on: push
env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_UDB3_JSON_SCHEMAS }}
jobs:
  split:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2
      # no tag
      - if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.1"
        with:
          package_directory: 'projects/uitdatabank/models'
          repository_organization: 'cultuurnet'
          repository_name: 'udb3-json-schemas'
          user_name: "dev-publiq"
          user_email: "dev@publiq.be"
          branch: ${{ steps.branch-name.outputs.current_branch }}
      # with tag
      - if: "startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.1"
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: 'projects/uitdatabank/models'
          repository_organization: 'cultuurnet'
          repository_name: 'udb3-json-schemas'
          user_name: "dev-publiq"
          user_email: "dev@publiq.be"
          branch: ${{ steps.branch-name.outputs.current_branch }}
