name: Split UDB3 JSON schemas
on: push
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2
      - name: Split
        uses: antalaron/action-splitsh@master
        with:
          split: 'cultuurnet/udb3-json-schemas'
          split_branch: ${{ steps.branch-name.outputs.current_branch }}
          split_deploy_key: ${{ secrets.DEPLOY_KEY_UDB3_JSON_SCHEMAS }}
          split_prefix: 'projects/uitdatabank/models'
