name: Split UDB3 JSON schemas
on:
  push:
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_UDB3_JSON_SCHEMAS }}
jobs:
  split:
    runs-on: ubuntu-latest
    name: Update cultuurnet/udb3-json-schemas repo
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Split
        uses: nxtlvlsoftware/git-subtree-action@1.1
        with:
          repo: 'cultuurnet/udb3-json-schemas'
          path: 'projects/uitdatabank/models'
          deploy_key: ${{ secrets.DEPLOY_KEY_UDB3_JSON_SCHEMAS }}
          force: true
